# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Marca\xe7\xe3o', 'verbose_name_plural': 'Marca\xe7\xf5es'},
        ),
        migrations.AddField(
            model_name='cidadao',
            name='numerobi',
            field=models.CharField(default=1, max_length=13, verbose_name='N\xba Bilhete de Identidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='agenda',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapi.Event', verbose_name='Marca\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='diasuteis',
            field=models.ManyToManyField(to='webapi.diasuteis', verbose_name='Servi\xe7os e Dias Ut\xe9is'),
        ),
    ]
